### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by mdleafg32** [gizemfitoz/ShoppingApp#1]
Hello Gizem,

sorry that I write here I have not found another option.

I would like to use parts of your shopping app but there is no license. I have already downloaded the code and run it looks great.

Is it possible to use the code or under which license do you want to do the whole thing?

Thank you very much

Best

Michael

**Comment by gizemfitoz** [comment]
Hello,

I've just added license file. You can use it!

Thanks!

**Comment by mdleafg32** [comment]
Thank you :-)

Wish you a happy new Year
